/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    addStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJNI_addStr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloJNI
 * Method:    print
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_print
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloJNI
 * Method:    incr
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_incr
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     HelloJNI
 * Method:    findSqrt
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_HelloJNI_findSqrt
  (JNIEnv *, jobject, jint);

/*
 * Class:     HelloJNI
 * Method:    getHostName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJNI_getHostName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
